export const reviews = [
  {
    id: 1,
    img: "Images/images.png",
    description:
      "Absolutely love it! The attention to detail in the selection of dry fruits and nuts is amazing, and they add a touch of luxury to my snack time.",
    name: "Sarojini",
    position: "Madurai",
  },
  {
    id: 2,
    img: "Images/images.png",
    description:
      "Great quality and variety! The chocolates and dates were a hit, and they made a perfect gift for my loved ones.",
    name: "Hema",
    position: "Coimbatore",
  },
  {
    id: 3,
    img: "Images/images.png",
    description:
      "Very happy with my purchase! The nuts were fresh and delicious, exceeding my expectations in terms of quality.",
    name: "Rajeshwari",
    position: "Salem",
  },
  {
    id: 4,
    img: "Images/images.png",
    description:
      "The perfect addition to my snack collection. The assortment of dry fruits, chocolates, and drinks fits perfectly with my taste.",
    name: "Sherin Taj",
    position: "Trichy",
  },
  {
    id: 5,
    img: "Images/images.png",
    description:
      "Beautifully packaged and delicious! The selection of nuts and dates is clearly curated with care, making them a cherished part of my daily routine.",
    name: "Sreema",
    position: "Tirunelveli",
  },
  {
    id: 6,
    img: "Images/images.png",
    description:
      "Such a thoughtful gift! The combination of dry fruits, chocolates, and drinks brought a smile to my face and was wonderfully received by the recipient.",
    name: "Raseena Farveen",
    position: "Chennai",
  },
  {
    id: 7,
    img: "Images/images.png",
    description:
      "Exactly what I was looking for. The quality of the nuts and the richness of the chocolates are even better in person, becoming a focal point in my snack time.",
    name: "Jagasree",
    position: "Vellore",
  },
  {
    id: 8,
    img: "Images/images.png",
    description:
      "Impressed with the variety and freshness. The selection of dates, nuts, and drinks is definitely worth it. I appreciate the careful craftsmanship.",
    name: "Menaga",
    position: "Erode",
  },
  {
    id: 9,
    img: "Images/images.png",
    description:
      "Wonderful experience! The whole process was seamless, from ordering to delivery. The chocolates and nuts were beautifully crafted and made a perfect gift.",
    name: "Aravindh",
    position: "Dindigul",
  },
  {
    id: 10,
    img: "Images/images.png",
    description:
      "Couldn't be happier with my purchase. The selection of dry fruits, dates, and drinks is a great addition to my collection and has exceeded my expectations.",
    name: "Shiva",
    position: "Kanyakumari",
  },
  {
    id: 11,
    img: "Images/images.png",
    description:
      "The dry fruits were top-notch, and the chocolates were a real treat! I'm very satisfied with the quality and packaging.",
    name: "Priya",
    position: "Thiruvannamalai",
  },
  {
    id: 12,
    img: "Images/images.png",
    description:
      "The variety offered is excellent! The dates and nuts were fresh, and the drinks added a refreshing touch to my day.",
    name: "Karthik",
    position: "Nagapattinam",
  },
  {
    id: 13,
    img: "Images/images.png",
    description:
      "High-quality products! The selection of chocolates, dry fruits, and nuts made for a perfect gift, and everyone loved it.",
    name: "Divya",
    position: "Virudhunagar",
  },
  {
    id: 14,
    img: "Images/images.png",
    description:
      "I'm impressed with the assortment and the freshness of the products. The drinks were a delightful addition to my snack time.",
    name: "Suresh",
    position: "Kanchipuram",
  },
  {
    id: 15,
    img: "Images/images.png",
    description:
      "The quality and variety of dry fruits and chocolates exceeded my expectations. I’ll definitely be ordering again!",
    name: "Latha",
    position: "Ramanathapuram",
  },
];


export const dryfruits = [
  {
    id: 1,
    name: "Strawberry",
    rating: 5,
    prices: {
      "100g": { currentPrice: "₹110", originalPrice: "₹120" },
      "250g": { currentPrice: "₹275", originalPrice: "₹300" },
      "500g": { currentPrice: "₹550", originalPrice: "₹600" },
      "1kg": { currentPrice: "₹1,100", originalPrice: "₹1,200" },
    },
    image: "Images/ProductsImages/dryFruits/strawberry.png",
  },
  {
    id: 2,
    name: "Cherry",
    rating: 5,
    prices: {
      "100g": { currentPrice: "₹75", originalPrice: "₹85" },
      "250g": { currentPrice: "₹188", originalPrice: "₹205" },
      "500g": { currentPrice: "₹375", originalPrice: "₹400" },
      "1kg": { currentPrice: "₹750", originalPrice: "₹800" },
    },
    image: "Images/ProductsImages/dryFruits/Cherry.png",
  },
  {
    id: 3,
    name: "Pineapple Coin",
    rating: 5,
    prices: {
      "100g": { currentPrice: "₹55", originalPrice: "₹65" },
      "250g": { currentPrice: "₹138", originalPrice: "₹150" },
      "500g": { currentPrice: "₹275", originalPrice: "₹300" },
      "1kg": { currentPrice: "₹550", originalPrice: "₹600" },
    },
    image: "Images/ProductsImages/dryFruits/PineappleCoin.png",
  },
  {
    id: 4,
    name: "Pineapple Ring",
    rating: 5,
    prices: {
      "100g": { currentPrice: "₹70", originalPrice: "₹80" },
      "250g": { currentPrice: "₹175", originalPrice: "₹190" },
      "500g": { currentPrice: "₹350", originalPrice: "₹380" },
      "1kg": { currentPrice: "₹700", originalPrice: "₹760" },
    },
    image: "Images/ProductsImages/dryFruits/PineappleRing.png",
  },
  {
    id: 5,
    name: "Mango Slice",
    rating: 5,
    prices: {
      "100g": { currentPrice: "₹65", originalPrice: "₹75" },
      "250g": { currentPrice: "₹163", originalPrice: "₹180" },
      "500g": { currentPrice: "₹325", originalPrice: "₹350" },
      "1kg": { currentPrice: "₹650", originalPrice: "₹700" },
    },
    image: "Images/ProductsImages/dryFruits/MangoSlice.png",
  },
  {
    id: 6,
    name: "Mango Toffee",
    rating: 5,
    prices: {
      "100g": { currentPrice: "₹50", originalPrice: "₹60" },
      "250g": { currentPrice: "₹125", originalPrice: "₹140" },
      "500g": { currentPrice: "₹250", originalPrice: "₹270" },
      "1kg": { currentPrice: "₹500", originalPrice: "₹550" },
    },
    image: "Images/ProductsImages/dryFruits/MangoToffee.png",
  },
  {
    id: 7,
    name: "Tamarind Toffee",
    rating: 5,
    prices: {
      "100g": { currentPrice: "₹30", originalPrice: "₹40" },
      "250g": { currentPrice: "₹75", originalPrice: "₹90" },
      "500g": { currentPrice: "₹150", originalPrice: "₹170" },
      "1kg": { currentPrice: "₹300", originalPrice: "₹350" },
    },
    image: "Images/ProductsImages/dryFruits/TamarindToffee.jpg",
  },
  {
    id: 8,
    name: "Kiwi",
    rating: 5,
    prices: {
      "100g": { currentPrice: "₹50", originalPrice: "₹60" },
      "250g": { currentPrice: "₹125", originalPrice: "₹140" },
      "500g": { currentPrice: "₹250", originalPrice: "₹270" },
      "1kg": { currentPrice: "₹500", originalPrice: "₹550" },
    },
    image: "Images/ProductsImages/dryFruits/Kiwi.png",
  },
  {
    id: 9,
    name: "Pamelo",
    rating: 5,
    prices: {
      "100g": { currentPrice: "₹58", originalPrice: "₹65" },
      "250g": { currentPrice: "₹145", originalPrice: "₹160" },
      "500g": { currentPrice: "₹290", originalPrice: "₹320" },
      "1kg": { currentPrice: "₹580", originalPrice: "₹640" },
    },
    image: "Images/ProductsImages/dryFruits/Pamelo.png",
  },
  {
    id: 10,
    name: "Apricot",
    rating: 5,
    prices: {
      "100g": { currentPrice: "₹150", originalPrice: "₹165" },
      "250g": { currentPrice: "₹375", originalPrice: "₹400" },
      "500g": { currentPrice: "₹750", originalPrice: "₹800" },
      "1kg": { currentPrice: "₹1,500", originalPrice: "₹1,600" },
    },
    image: "Images/ProductsImages/dryFruits/Apricot.png",
  },
  {
    id: 11,
    name: "Dried Apricot",
    rating: 5,
    prices: {
      "100g": { currentPrice: "₹80", originalPrice: "₹90" },
      "250g": { currentPrice: "₹200", originalPrice: "₹220" },
      "500g": { currentPrice: "₹400", originalPrice: "₹430" },
      "1kg": { currentPrice: "₹800", originalPrice: "₹850" },
    },
    image: "Images/ProductsImages/dryFruits/DriedApricot.jpg",
  },
  {
    id: 12,
    name: "Prunes",
    rating: 5,
    prices: { "100g": { currentPrice: "₹90", originalPrice: "₹100" }, "250g": { currentPrice: "₹225", originalPrice: "₹245" }, "500g": { currentPrice: "₹450", originalPrice: "₹480" }, "1kg": { currentPrice: "₹900", originalPrice: "₹950" } },
    image: "Images/ProductsImages/dryFruits/Prunes.png",
  },
  {
    id: 13,
    name: "Black Currant",
    rating: 5,
    prices: { "100g": { currentPrice: "₹60", originalPrice: "₹70" }, "250g": { currentPrice: "₹150", originalPrice: "₹165" }, "500g": { currentPrice: "₹300", originalPrice: "₹330" }, "1kg": { currentPrice: "₹600", originalPrice: "₹660" } },
    image: "Images/ProductsImages/dryFruits/BlackCurrant.png",
  },
  {
    id: 14,
    name: "Blueberry",
    rating: 5,
    prices: { "100g": { currentPrice: "₹150", originalPrice: "₹165" }, "250g": { currentPrice: "₹375", originalPrice: "₹400" }, "500g": { currentPrice: "₹750", originalPrice: "₹800" }, "1kg": { currentPrice: "₹1,500", originalPrice: "₹1,600" } },
    image: "Images/ProductsImages/dryFruits/Blueberry.png",
  },
  {
    id: 15,
    name: "Cranberry",
    rating: 5,
    prices: { "100g": { currentPrice: "₹70", originalPrice: "₹80" }, "250g": { currentPrice: "₹175", originalPrice: "₹190" }, "500g": { currentPrice: "₹350", originalPrice: "₹380" }, "1kg": { currentPrice: "₹700", originalPrice: "₹760" } },
    image: "Images/ProductsImages/dryFruits/Craneberry.png",
  },
  {
    id: 16,
    name: "Raspberry",
    rating: 5,
    prices: { "100g": { currentPrice: "₹300", originalPrice: "₹330" }, "250g": { currentPrice: "₹750", originalPrice: "₹800" }, "500g": { currentPrice: "₹1,500", originalPrice: "₹1,600" }, "1kg": { currentPrice: "₹3,000", originalPrice: "₹3,200" } },
    image: "Images/ProductsImages/dryFruits/Raspberry.png",
  },
  {
    id: 17,
    name: "Blackberry",
    rating: 5,
    prices: { "100g": { currentPrice: "₹240", originalPrice: "₹260" }, "250g": { currentPrice: "₹600", originalPrice: "₹650" }, "500g": { currentPrice: "₹1,200", originalPrice: "₹1,300" }, "1kg": { currentPrice: "₹2,400", originalPrice: "₹2,600" } },
    image: "Images/ProductsImages/dryFruits/Blackberry.png",
  },
  {
    id: 18,
    name: "Goji Berry",
    rating: 5,
    prices: { "100g": { currentPrice: "₹130", originalPrice: "₹145" }, "250g": { currentPrice: "₹325", originalPrice: "₹350" }, "500g": { currentPrice: "₹650", originalPrice: "₹700" }, "1kg": { currentPrice: "₹1,300", originalPrice: "₹1,400" } },
    image: "Images/ProductsImages/dryFruits/Gojiberry.png",
  },
  {
    id: 19,
    name: "Yellow Peach",
    rating: 5,
    prices: { "100g": { currentPrice: "₹60", originalPrice: "₹70" }, "250g": { currentPrice: "₹150", originalPrice: "₹165" }, "500g": { currentPrice: "₹300", originalPrice: "₹330" }, "1kg": { currentPrice: "₹600", originalPrice: "₹660" } },
    image: "Images/ProductsImages/dryFruits/YellowPeach.png",
  },
  {
    id: 20,
    name: "Honey Amla",
    rating: 5,
    prices: { "100g": { currentPrice: "₹50", originalPrice: "₹60" }, "250g": { currentPrice: "₹125", originalPrice: "₹140" }, "500g": { currentPrice: "₹250", originalPrice: "₹270" }, "1kg": { currentPrice: "₹500", originalPrice: "₹550" } },
    image: "Images/ProductsImages/dryFruits/HoneyAmla.png",
  },
  {
    id: 21,
    name: "Dried Amla",
    rating: 5,
    prices: { "100g": { currentPrice: "₹35", originalPrice: "₹40" }, "250g": { currentPrice: "₹88", originalPrice: "₹95" }, "500g": { currentPrice: "₹175", originalPrice: "₹190" }, "1kg": { currentPrice: "₹350", originalPrice: "₹380" } },
    image: "Images/ProductsImages/dryFruits/DriedAmla.png",
  },
  {
    id: 22,
    name: "Pepper Amla",
    rating: 5,
    prices: { "100g": { currentPrice: "₹50", originalPrice: "₹60" }, "250g": { currentPrice: "₹125", originalPrice: "₹140" }, "500g": { currentPrice: "₹250", originalPrice: "₹270" }, "1kg": { currentPrice: "₹500", originalPrice: "₹550" } },
    image: "Images/ProductsImages/dryFruits/PepperAmla.png",
  },
  {
    id: 23,
    name: "Karupatti Amla",
    rating: 5,
    prices: { "100g": { currentPrice: "₹50", originalPrice: "₹60" }, "250g": { currentPrice: "₹125", originalPrice: "₹140" }, "500g": { currentPrice: "₹250", originalPrice: "₹270" }, "1kg": { currentPrice: "₹500", originalPrice: "₹550" } },
    image: "Images/ProductsImages/dryFruits/KarupattiAmla.png",
  },
  {
    id: 24,
    name: "Vegetable Chips",
    rating: 5,
    prices: { "100g": { currentPrice: "₹100", originalPrice: "₹110" }, "250g": { currentPrice: "₹250", originalPrice: "₹275" }, "500g": { currentPrice: "₹500", originalPrice: "₹550" }, "1kg": { currentPrice: "₹999", originalPrice: "₹1,100" } },
    image: "Images/ProductsImages/dryFruits/VegetableChips.png",
  },
  {
    id: 25,
    name: "Fruit Chips",
    rating: 5,
    prices: { "100g": { currentPrice: "₹110", originalPrice: "₹120" }, "250g": { currentPrice: "₹275", originalPrice: "₹300" }, "500g": { currentPrice: "₹550", originalPrice: "₹600" }, "1kg": { currentPrice: "₹1,100", originalPrice: "₹1,200" } },
    image: "Images/ProductsImages/dryFruits/FruitChips.png",
  },
];

export const nuts = [
  {
    id: 26,
    name: "Almond Regular",
    rating: 5,
    prices: {
      "100g": { currentPrice: "₹96", originalPrice: "₹110" },
      "250g": { currentPrice: "₹241", originalPrice: "₹260" },
      "500g": { currentPrice: "₹482", originalPrice: "₹500" },
      "1kg": { currentPrice: "₹965", originalPrice: "₹1000" },
    },
    image: "Images/ProductsImages/nuts/Almond.jpg",
  },
  {
    id: 27,
    name: "Almond Special",
    rating: 5,
    prices: {
      "100g": { currentPrice: "₹112", originalPrice: "₹130" },
      "250g": { currentPrice: "₹280", originalPrice: "₹300" },
      "500g": { currentPrice: "₹560", originalPrice: "₹575" },
      "1kg": { currentPrice: "₹1,120", originalPrice: "₹1,150" },
    },
    image: "Images/ProductsImages/nuts/Almond.jpg",
  },
  {
    id: 28,
    name: "Cashew 240",
    rating: 4,
    prices: {
      "100g": { currentPrice: "₹92", originalPrice: "₹100" },
      "250g": { currentPrice: "₹230", originalPrice: "₹250" },
      "500g": { currentPrice: "₹460", originalPrice: "₹490" },
      "1kg": { currentPrice: "₹920", originalPrice: "₹950" },
    },
    image: "Images/ProductsImages/nuts/Cashew.png",
  },
  {
    id: 29,
    name: "Cashew 320",
    rating: 4,
    prices: {
      "100g": { currentPrice: "₹82", originalPrice: "₹90" },
      "250g": { currentPrice: "₹205", originalPrice: "₹225" },
      "500g": { currentPrice: "₹410", originalPrice: "₹430" },
      "1kg": { currentPrice: "₹820", originalPrice: "₹850" },
    },
    image: "Images/ProductsImages/nuts/Cashew.png",
  },
  {
    id: 30,
    name: "Black Seed Grapes",
    rating: 4,
    prices: {
      "100g": { currentPrice: "₹68", originalPrice: "₹80" },
      "250g": { currentPrice: "₹170", originalPrice: "₹200" },
      "500g": { currentPrice: "₹340", originalPrice: "₹350" },
      "1kg": { currentPrice: "₹680", originalPrice: "₹700" },
    },
    image: "/Images/ProductsImages/nuts/BlackSeedGrapes.png",
  },
  {
    id: 31,
    name: "Black Seedless",
    rating: 4,
    prices: {
      "100g": { currentPrice: "₹50", originalPrice: "₹60" },
      "250g": { currentPrice: "₹125", originalPrice: "₹130" },
      "500g": { currentPrice: "₹250", originalPrice: "₹275" },
      "1kg": { currentPrice: "₹500", originalPrice: "₹550" },
    },
    image: "/Images/ProductsImages/nuts/BlackSeedles.png",
  },
  {
    id: 32,
    name: "Walnut",
    rating: 4,
    prices: {
      "100g": { currentPrice: "₹160", originalPrice: "₹175" },
      "250g": { currentPrice: "₹400", originalPrice: "₹420" },
      "500g": { currentPrice: "₹800", originalPrice: "₹850" },
      "1kg": { currentPrice: "₹1,600", originalPrice: "₹1,700" },
    },
    image: "Images/ProductsImages/nuts/Walnut.png",
  },
  {
    id: 33,
    name: "Makhana Regular",
    rating: 4,
    prices: {
      "100g": { currentPrice: "₹90", originalPrice: "₹100" },
      "250g": { currentPrice: "₹225", originalPrice: "₹230" },
      "500g": { currentPrice: "₹450", originalPrice: "₹475" },
      "1kg": { currentPrice: "₹900", originalPrice: "₹950" },
    },
    image: "Images/ProductsImages/nuts/Makhana.png",
  },
  {
    id: 34,
    name: "Makhana Bold",
    rating: 4,
    prices: {
      "100g": { currentPrice: "₹140", originalPrice: "₹150" },
      "250g": { currentPrice: "₹350", originalPrice: "₹375" },
      "500g": { currentPrice: "₹700", originalPrice: "₹750" },
      "1kg": { currentPrice: "₹1,400", originalPrice: "₹1,500" },
    },
    image: "Images/ProductsImages/nuts/Makhana.png",
  },
  {
    id: 35,
    name: "Indian Raisin",
    rating: 4,
    prices: {
      "100g": { currentPrice: "₹50", originalPrice: "₹60" },
      "250g": { currentPrice: "₹125", originalPrice: "₹130" },
      "500g": { currentPrice: "₹250", originalPrice: "₹275" },
      "1kg": { currentPrice: "₹500", originalPrice: "₹550" },
    },
    image: "Images/ProductsImages/nuts/IndianRaisin.png",
  },
  {
    id: 36,
    name: "Green Pista",
    rating: 4,
    prices: {
      "100g": { currentPrice: "₹275", originalPrice: "₹300" },
      "250g": { currentPrice: "₹687", originalPrice: "₹700" },
      "500g": { currentPrice: "₹1,375", originalPrice: "₹1,400" },
      "1kg": { currentPrice: "₹2,750", originalPrice: "₹2,850" },
    },
    image: "Images/ProductsImages/nuts/GreenPistachio.png",
  },
  {
    id: 37,
    name: "Roasted Pista",
    rating: 4,
    prices: {
      "100g": { currentPrice: "₹155", originalPrice: "₹175" },
      "250g": { currentPrice: "₹387", originalPrice: "₹400" },
      "500g": { currentPrice: "₹775", originalPrice: "₹800" },
      "1kg": { currentPrice: "₹1,550", originalPrice: "₹1,650" },
    },
    image: "Images/ProductsImages/nuts/Pistachio.jpeg",
  },
  {
    id: 38,
    name: "Roasted Pista Bold",
    rating: 4,
    prices: {
      "100g": { currentPrice: "₹165", originalPrice: "₹180" },
      "250g": { currentPrice: "₹412", originalPrice: "₹430" },
      "500g": { currentPrice: "₹825", originalPrice: "₹850" },
      "1kg": { currentPrice: "₹1,650", originalPrice: "₹1,750" },
    },
    image: "Images/ProductsImages/nuts/Pistachio.jpeg",
  },
  {
    id: 39,
    name: "Brazil Nuts",
    rating: 4,
    prices: {
      "100g": { currentPrice: "₹320", originalPrice: "₹350" },
      "250g": { currentPrice: "₹800", originalPrice: "₹830" },
      "500g": { currentPrice: "₹1,600", originalPrice: "₹1,650" },
      "1kg": { currentPrice: "₹3,200", originalPrice: "₹3,300" },
    },
    image: "Images/ProductsImages/nuts/BrazilNuts.jpeg",
  },
  {
    id: 40,
    name: "Hazle Nut",
    rating: 4,
    prices: {
      "100g": { currentPrice: "₹250", originalPrice: "₹270" },
      "250g": { currentPrice: "₹625", originalPrice: "₹650" },
      "500g": { currentPrice: "₹1,250", originalPrice: "₹1,300" },
      "1kg": { currentPrice: "₹2,500", originalPrice: "₹2,600" },
    },
    image: "Images/ProductsImages/nuts/HazleNuts.jpeg",
  },
  {
    id: 41,
    name: "Pecan Nuts",
    rating: 3,
    prices: {
      "100g": { currentPrice: "₹220", originalPrice: "₹230" },
      "250g": { currentPrice: "₹550", originalPrice: "₹575" },
      "500g": { currentPrice: "₹1,100", originalPrice: "₹1,150" },
      "1kg": { currentPrice: "₹2,200", originalPrice: "₹2,250" },
    },
    image: "Images/ProductsImages/nuts/PecanNuts.png",
  },
  {
    id: 42,
    name: "Macadamia",
    rating: 3,
    prices: {
      "100g": { currentPrice: "₹320", originalPrice: "₹330" },
      "250g": { currentPrice: "₹800", originalPrice: "₹825" },
      "500g": { currentPrice: "₹1,600", originalPrice: "₹1,750" },
      "1kg": { currentPrice: "₹3,200", originalPrice: "₹3,300" },
    },
    image: "Images/ProductsImages/nuts/Macadamia.png",
  },
  {
    id: 43,
    name: "Pepper Cashew",
    rating: 4,
    prices: {
      "100g": { currentPrice: "₹100", originalPrice: "₹110" },
      "250g": { currentPrice: "₹250", originalPrice: "₹275" },
      "500g": { currentPrice: "₹500", originalPrice: "₹550" },
      "1kg": { currentPrice: "₹1,000", originalPrice: "₹1,100" },
    },
    image: "Images/ProductsImages/nuts/PepperCashew.png",
  },
  {
    id: 44,
    name: "Salted Cashew",
    rating: 4,
    prices: {
      "100g": { currentPrice: "₹100", originalPrice: "₹110" },
      "250g": { currentPrice: "₹250", originalPrice: "₹275" },
      "500g": { currentPrice: "₹500", originalPrice: "₹550" },
      "1kg": { currentPrice: "₹1,000", originalPrice: "₹1,100" },
    },
    image: "Images/ProductsImages/nuts/SaltedCashew.png",
  },
  {
    id: 45,
    name: "Periperi Cashew",
    rating: 4,
    prices: {
      "100g": { currentPrice: "₹100", originalPrice: "₹110" },
      "250g": { currentPrice: "₹250", originalPrice: "₹275" },
      "500g": { currentPrice: "₹500", originalPrice: "₹550" },
      "1kg": { currentPrice: "₹1,000", originalPrice: "₹1,100" },
    },
    image: "Images/ProductsImages/nuts/PeriperiCashew.png",
  },
  {
    id: 46,
    name: "Green Chilli Cashew",
    rating: 4,
    prices: {
      "100g": { currentPrice: "₹100", originalPrice: "₹110" },
      "250g": { currentPrice: "₹250", originalPrice: "₹275" },
      "500g": { currentPrice: "₹500", originalPrice: "₹550" },
      "1kg": { currentPrice: "₹1,000", originalPrice: "₹1,100" },
    },
    image: "Images/ProductsImages/nuts/GreenchilliCashew.png",
  },
  {
    id: 47,
    name: "Chilli Cashew",
    rating: 4,
    prices: {
      "100g": { currentPrice: "₹100", originalPrice: "₹110" },
      "250g": { currentPrice: "₹250", originalPrice: "₹275" },
      "500g": { currentPrice: "₹500", originalPrice: "₹550" },
      "1kg": { currentPrice: "₹1,000", originalPrice: "₹1,100" },
    },
    image: "Images/ProductsImages/nuts/ChilliCashew.png",
  },
  {
    id: 48,
    name: "Salted Almond",
    rating: 4,
    prices: {
      "100g": { currentPrice: "₹115", originalPrice: "₹130" },
      "250g": { currentPrice: "₹287", originalPrice: "₹300" },
      "500g": { currentPrice: "₹575", originalPrice: "₹599" },
      "1kg": { currentPrice: "₹1,150", originalPrice: "₹1,300" },
    },
    image: "Images/ProductsImages/nuts/SaltedAlmond.png",
  },
  {
    id: 49,
    name: "Millet Protein",
    rating: 4,
    prices: {
      "100g": { currentPrice: "₹70", originalPrice: "₹75" },
      "250g": { currentPrice: "₹175", originalPrice: "₹180" },
      "500g": { currentPrice: "₹350", originalPrice: "₹375" },
      "1kg": { currentPrice: "₹700", originalPrice: "₹800" },
    },
    image: "Images/ProductsImages/nuts/MilletProtein.png",
  },
];

export const seeds = [
  {
    id: 50,
    name: "Pumpkin Seed",
    rating: 5,
    prices: {
      "100g": { currentPrice: "₹62", originalPrice: "₹70" },
      "250g": { currentPrice: "₹155", originalPrice: "₹170" },
      "500g": { currentPrice: "₹310", originalPrice: "₹340" },
      "1kg": { currentPrice: "₹620", originalPrice: "₹680" },
    },
    image: "Images/ProductsImages/seeds/PumpkinSeeds.png",
  },
  {
    id: 51,
    name: "Sunflower Seed",
    rating: 5,
    prices: {
      "100g": { currentPrice: "₹35", originalPrice: "₹40" },
      "250g": { currentPrice: "₹88", originalPrice: "₹95" },
      "500g": { currentPrice: "₹175", originalPrice: "₹190" },
      "1kg": { currentPrice: "₹350", originalPrice: "₹380" },
    },
    image: "Images/ProductsImages/seeds/SunflowerSeeds.png",
  },
  {
    id: 52,
    name: "Watermelon Seed",
    rating: 5,
    prices: {
      "100g": { currentPrice: "₹85", originalPrice: "₹95" },
      "250g": { currentPrice: "₹213", originalPrice: "₹230" },
      "500g": { currentPrice: "₹425", originalPrice: "₹460" },
      "1kg": { currentPrice: "₹850", originalPrice: "₹920" },
    },
    image: "Images/ProductsImages/seeds/WatermelonSeeds.png",
  },
  {
    id: 53,
    name: "Chia Seeds",
    rating: 5,
    prices: {
      "100g": { currentPrice: "₹48", originalPrice: "₹55" },
      "250g": { currentPrice: "₹120", originalPrice: "₹135" },
      "500g": { currentPrice: "₹240", originalPrice: "₹260" },
      "1kg": { currentPrice: "₹480", originalPrice: "₹520" },
    },
    image: "Images/ProductsImages/seeds/ChiaSeeds.png",
  },
  {
    id: 54,
    name: "Flax Seed",
    rating: 5,
    prices: {
      "100g": { currentPrice: "₹30", originalPrice: "₹35" },
      "250g": { currentPrice: "₹75", originalPrice: "₹85" },
      "500g": { currentPrice: "₹150", originalPrice: "₹170" },
      "1kg": { currentPrice: "₹300", originalPrice: "₹340" },
    },
    image: "Images/ProductsImages/seeds/FlaxSeeds.png",
  },
  {
    id: 55,
    name: "Cucumber Seed",
    rating: 5,
    prices: {
      "100g": { currentPrice: "₹80", originalPrice: "₹90" },
      "250g": { currentPrice: "₹200", originalPrice: "₹220" },
      "500g": { currentPrice: "₹400", originalPrice: "₹440" },
      "1kg": { currentPrice: "₹800", originalPrice: "₹880" },
    },
    image: "Images/ProductsImages/seeds/CucumberSeeds.png",
  },
  {
    id: 56,
    name: "Halim Seed",
    rating: 5,
    prices: {
      "100g": { currentPrice: "₹25", originalPrice: "₹30" },
      "250g": { currentPrice: "₹63", originalPrice: "₹70" },
      "500g": { currentPrice: "₹125", originalPrice: "₹140" },
      "1kg": { currentPrice: "₹250", originalPrice: "₹280" },
    },
    image: "Images/ProductsImages/seeds/HalimSeeds.png",
  },
  {
    id: 57,
    name: "Basil (Sabja) Seed",
    rating: 5,
    prices: {
      "100g": { currentPrice: "₹40", originalPrice: "₹45" },
      "250g": { currentPrice: "₹100", originalPrice: "₹110" },
      "500g": { currentPrice: "₹200", originalPrice: "₹220" },
      "1kg": { currentPrice: "₹400", originalPrice: "₹440" },
    },
    image: "Images/ProductsImages/seeds/SabjaSeeds.png",
  },
  {
    id: 58,
    name: "White Sesame",
    rating: 5,
    prices: {
      "100g": { currentPrice: "₹30", originalPrice: "₹35" },
      "250g": { currentPrice: "₹75", originalPrice: "₹85" },
      "500g": { currentPrice: "₹150", originalPrice: "₹170" },
      "1kg": { currentPrice: "₹300", originalPrice: "₹340" },
    },
    image: "Images/ProductsImages/seeds/WhiteSesameSeeds.png",
  },
  {
    id: 59,
    name: "Mixed Roasted Seeds",
    rating: 5,
    prices: {
      "100g": { currentPrice: "₹90", originalPrice: "₹100" },
      "250g": { currentPrice: "₹225", originalPrice: "₹245" },
      "500g": { currentPrice: "₹450", originalPrice: "₹490" },
      "1kg": { currentPrice: "₹900", originalPrice: "₹980" },
    },
    image: "Images/ProductsImages/seeds/MixedRoastedSeeds.png",
  },
];

export const dates = [
  {
    id: 60,
    name: "Kimia Dates",
    rating: 5,
    prices: {
      "1 Box": {
        currentPrice: "₹180",
        originalPrice: "₹200",
      },
    },
    image: "Images/ProductsImages/dates/KimiaDates.png",
  },
  {
    id: 61,
    name: "Muscat Dates",
    rating: 5,
    prices: {
      "100g": { currentPrice: "₹38", originalPrice: "₹42" },
      "250g": { currentPrice: "₹95", originalPrice: "₹105" },
      "500g": { currentPrice: "₹190", originalPrice: "₹210" },
      "1kg": { currentPrice: "₹380", originalPrice: "₹420" },
    },
    image: "Images/ProductsImages/dates/MuscatDates.png",
  },
  {
    id: 62,
    name: "Kalima Dates",
    rating: 5,
    prices: {
      "100g": { currentPrice: "₹75", originalPrice: "₹82" },
      "250g": { currentPrice: "₹188", originalPrice: "₹205" },
      "500g": { currentPrice: "₹375", originalPrice: "₹410" },
      "1kg": { currentPrice: "₹750", originalPrice: "₹820" },
    },
    image: "Images/ProductsImages/dates/KalimaDates.png",
  },
  {
    id: 63,
    name: "Mabroom Dates",
    rating: 5,
    prices: {
      "100g": { currentPrice: "₹120", originalPrice: "₹130" },
      "250g": { currentPrice: "₹300", originalPrice: "₹325" },
      "500g": { currentPrice: "₹600", originalPrice: "₹650" },
      "1kg": { currentPrice: "₹1,200", originalPrice: "₹1,300" },
    },
    image: "Images/ProductsImages/dates/MabroomDates.png",
  },
  {
    id: 64,
    name: "Ajwa Bold Dates",
    rating: 5,
    prices: {
      "100g": { currentPrice: "₹120", originalPrice: "₹130" },
      "250g": { currentPrice: "₹300", originalPrice: "₹325" },
      "500g": { currentPrice: "₹600", originalPrice: "₹650" },
      "1kg": { currentPrice: "₹1,200", originalPrice: "₹1,300" },
    },
    image: "Images/ProductsImages/dates/AjwaBoldDates.png",
  },
  {
    id: 65,
    name: "Ajwa Regular",
    rating: 5,
    prices: {
      "100g": { currentPrice: "₹70", originalPrice: "₹80" },
      "250g": { currentPrice: "₹175", originalPrice: "₹190" },
      "500g": { currentPrice: "₹350", originalPrice: "₹380" },
      "1kg": { currentPrice: "₹700", originalPrice: "₹760" },
    },
    image: "Images/ProductsImages/dates/AjwaDates.png",
  },
  {
    id: 66,
    name: "Medjool Dates",
    rating: 5,
    prices: {
      "100g": { currentPrice: "₹160", originalPrice: "₹175" },
      "250g": { currentPrice: "₹400", originalPrice: "₹430" },
      "500g": { currentPrice: "₹800", originalPrice: "₹860" },
      "1kg": { currentPrice: "₹1,600", originalPrice: "₹1,750" },
    },
    image: "Images/ProductsImages/dates/MedjuolDates.png",
  },
  {
    id: 67,
    name: "Zahadi Dates",
    rating: 5,
    prices: {
      "100g": { currentPrice: "₹19", originalPrice: "₹22" },
      "250g": { currentPrice: "₹48", originalPrice: "₹55" },
      "500g": { currentPrice: "₹95", originalPrice: "₹105" },
      "1kg": { currentPrice: "₹190", originalPrice: "₹210" },
    },
    image: "Images/ProductsImages/dates/ZahadiDates.png",
  },
  {
    id: 68,
    name: "Tunisian Dates",
    rating: 5,
    prices: {
      "100g": { currentPrice: "₹40", originalPrice: "₹45" },
      "250g": { currentPrice: "₹100", originalPrice: "₹110" },
      "500g": { currentPrice: "₹200", originalPrice: "₹220" },
      "1kg": { currentPrice: "₹400", originalPrice: "₹440" },
    },
    image: "Images/ProductsImages/dates/TunisianDates.png",
  },
  {
    id: 69,
    name: "Barari Dates",
    rating: 5,
    prices: {
      "100g": { currentPrice: "₹23", originalPrice: "₹26" },
      "250g": { currentPrice: "₹58", originalPrice: "₹65" },
      "500g": { currentPrice: "₹115", originalPrice: "₹125" },
      "1kg": { currentPrice: "₹230", originalPrice: "₹250" },
    },
    image: "Images/ProductsImages/dates/BarariDates.png",
  },
  {
    id: 70,
    name: "Amber Dates",
    rating: 5,
    prices: {
      "100g": { currentPrice: "₹120", originalPrice: "₹130" },
      "250g": { currentPrice: "₹300", originalPrice: "₹325" },
      "500g": { currentPrice: "₹600", originalPrice: "₹650" },
      "1kg": { currentPrice: "₹1,200", originalPrice: "₹1,300" },
    },
    image: "Images/ProductsImages/dates/AmberDates.png",
  },
  {
    id: 71,
    name: "Smart Seedless Dates",
    rating: 5,
    prices: {
      "100g": { currentPrice: "₹120", originalPrice: "₹130" },
      "250g": { currentPrice: "₹300", originalPrice: "₹325" },
      "500g": { currentPrice: "₹600", originalPrice: "₹650" },
      "1kg": { currentPrice: "₹1,200", originalPrice: "₹1,300" },
    },
    image: "Images/ProductsImages/dates/SmartSeedlessDates.png",
  },
];


export const combo = [
  {
    id: 72,
    name: "Combo Offer",
    rating: 5,
    contents: ["Pumpkin", "Sunflower", "Chia", "Flax", "Watermelon", "Cucumber"],
    prices: {
      "1 Box": { currentPrice: "₹299", originalPrice: "₹400" },
    },
    image: "Images/BannerImages/combo1.png",
  }
];